# Generated by Django 4.0.3 on 2022-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.CharField(max_length=250),
        ),
    ]
