# Generated by Django 4.0.3 on 2022-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0002_alter_candidate_max_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('jobname', models.CharField(max_length=250)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('min_salary', models.CharField(max_length=250)),
                ('max_salary', models.CharField(max_length=250)),
                ('highestedu', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(max_length=50)),
                ('jobdescription', models.TextField(max_length=500)),
                ('logo_pic', models.ImageField(default='', upload_to='companyapp/img/Apply')),
            ],
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(max_length=250),
        ),
    ]
