# Generated by Django 4.0.3 on 2022-04-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0003_applylist_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='city',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='jobdescription',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='jobname',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='logo_pic',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='state',
        ),
        migrations.AddField(
            model_name='applylist',
            name='candidate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jagirapp.candidate'),
        ),
        migrations.AddField(
            model_name='applylist',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jagirapp.jobdetails'),
        ),
        migrations.AddField(
            model_name='applylist',
            name='resume',
            field=models.ImageField(default='', upload_to='app/resume'),
        ),
    ]
