# Generated by Django 4.0.3 on 2022-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0004_remove_applylist_city_remove_applylist_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.CharField(max_length=500),
        ),
    ]
