# Generated by Django 4.0.3 on 2022-04-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jagirapp.usermaster'),
        ),
    ]
