# Generated by Django 4.0.3 on 2022-04-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0007_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
    ]
