# Generated by Django 4.0.3 on 2022-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0010_alter_jobdetails_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='expiredate',
            field=models.DateField(default='', max_length=50),
        ),
    ]
