# Generated by Django 4.0.3 on 2022-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0015_remove_jobdetails_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='expiredate',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='jobtype',
            field=models.CharField(default='', max_length=250),
        ),
    ]
