# Generated by Django 4.0.3 on 2022-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagirapp', '0016_jobdetails_expiredate_jobdetails_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='expiredate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
